# Generated by Django 5.1.5 on 2025-01-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(default='Client Plus', max_length=50)),
                ('Year', models.IntegerField()),
                ('MonthNo', models.IntegerField()),
                ('Day', models.IntegerField()),
                ('Month', models.CharField(max_length=20)),
                ('ConsultantID', models.IntegerField()),
                ('Consultant', models.CharField(max_length=100)),
                ('Client', models.CharField(max_length=200)),
                ('ActivityType', models.CharField(max_length=10)),
                ('WorkingHours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('NOTES', models.TextField()),
            ],
            options={
                'verbose_name': 'Historical Data',
                'verbose_name_plural': 'Historical Data',
            },
        ),
        migrations.RenameField(
            model_name='client',
            old_name='activity',
            new_name='Activity',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='CLIENTNAME',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='status',
            new_name='St',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='type',
            new_name='Type',
        ),
        migrations.CreateModel(
            name='ConsultantDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consultant', models.CharField(max_length=100)),
                ('ConsultantID', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('DealDays', models.IntegerField()),
            ],
            options={
                'unique_together': {('Consultant', 'Year', 'Month')},
            },
        ),
        migrations.CreateModel(
            name='ConsultantVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consultant', models.CharField(max_length=100)),
                ('Days', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Month', models.IntegerField()),
            ],
            options={
                'unique_together': {('Consultant', 'Year', 'Month')},
            },
        ),
        migrations.CreateModel(
            name='PagePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Page', models.CharField(max_length=100)),
                ('Access', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], max_length=4)),
            ],
            options={
                'unique_together': {('User', 'Page')},
            },
        ),
    ]
