# Generated by Django 5.1.5 on 2025-01-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_histdata_rename_activity_client_activity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['CLIENTNAME']},
        ),
        migrations.AlterField(
            model_name='histdata',
            name='NOTES',
            field=models.TextField(blank=True, null=True),
        ),
    ]
